TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 2.0
  min_vel_x: -2.0

  max_vel_theta:  0.3
  min_vel_theta: -0.3
  min_in_place_vel_theta: 0.1

  acc_lim_x: 2.0
  acc_lim_y: 0.0
  acc_lim_theta: 1.0

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.5
  yaw_goal_tolerance: 0.5

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 1.0
  vx_samples: 10
  vtheta_samples: 10
  sim_granularity: 0.05
